language: node_js
os: linux
node_js:
- node
script:
- npm test
before_deploy:
- npm run build
- cd dist
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "*"
  cleanup: false
  on:
    tags: true