language: node_js
os: linux
node_js:
- node
script:
- npm test
branches:
  # expected format: v1.0.0
  on:
  - /^v\d+(\.\d+)+$/
  - master
before_deploy:
- npm run build
- cd dist
 #- zip og-${TRAVIS_TAG}.zip *
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  #file: og-${TRAVIS_TAG}.zip
  file: 
  - "*.js"
  - "*.css"
  skip_cleanup: true
  on:
    tags: true