language: node_js
os: linux
node_js:
- node
script:
- npm test
before_deploy:
- npm run build
- ls -l
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "dist/*/**"
  skip_cleanup: true
  on:
    tags: true