language: node_js
os: linux
node_js:
- node
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: releases
  token: $GITHUB_TOKEN
  file_glob: true
  file: "/home/travis/build/openglobus/openglobus/dist/*"
  cleanup: true
  on:
    tags: true