language: node_js

os: linux

node_js:
  - node

branches:
  only:
    - master

script:
  - npm test
  - npm run-script build

 deploy:
    provider: releases
    api_key: ${GITHUB_API_KEY}
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
        tags: true